version: '3.9'
services:
  db:
    image: postgres:16-alpine
#    environment:
#      - POSTGRES_HOST_AUTH_METHOD=trust
#      - POSTGRES_USER=test
#      - POSTGRES_PASSWORD=123
#      - POSTGRES_DB=new_test_db
    env_file:
      - ./.env_prod
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    build: .
    command: sh -c "sleep 5 && alembic upgrade head && python bot/run.py"
    env_file:
      - ./.env_prod
    restart: always
    depends_on:
      - db

volumes:
  pgdata:
